# Generated by Django 3.2.11 on 2022-01-31 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Franchise',
                'verbose_name_plural': 'Franchises',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ListFranchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listfranchise', to='core.franchise')),
            ],
            options={
                'verbose_name': 'ListFranchise',
                'verbose_name_plural': 'ListFranchises',
                'ordering': ['id'],
            },
        ),
    ]
