# Generated by Django 3.2.11 on 2022-01-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listfranchise',
            options={},
        ),
    ]
